version: "3"
services:
  db:
    image: postgres
    container_name: postgres-docker
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: shogoRingo
      POSTGRES_DB: todo
    ports:
      - "15432:5432"
    volumes:
      - database:/var/lib/postgresql/data
#      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  database:
    driver: local