export const FETCH_TODO = "FETCH_TODO"
export const ADD_TODO = "ADD_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const DELETE_TODOS = "DELETE_TODOS"
export const UPDATE_TODO = "UPDATE_TODO"
